export const getThemeColors = (color: string) => {
  const colors = {
    blue: {
      primary: "from-blue-600 to-purple-600",
      secondary: "from-blue-500 to-purple-500",
      text: "text-blue-700 dark:text-blue-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-blue-600 dark:hover:text-blue-400",
      gradient: "from-blue-600 via-purple-600 to-pink-600",
      from: "from-blue-500",
      to: "to-purple-500",
      darkFrom: "dark:from-blue-500",
      darkTo: "dark:to-purple-900",
    },
    green: {
      primary: "from-green-600 to-teal-600",
      secondary: "from-green-500 to-teal-500",
      text: "text-green-700 dark:text-green-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-green-600 dark:hover:text-green-400",
      gradient: "from-green-600 via-teal-600 to-cyan-600",
      from: "from-green-500",
      to: "to-teal-500",
      darkFrom: "dark:from-green-500",
      darkTo: "dark:to-teal-900",
    },
    purple: {
      primary: "from-purple-600 to-pink-600",
      secondary: "from-purple-500 to-pink-500",
      text: "text-purple-700 dark:text-purple-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-purple-600 dark:hover:text-purple-400",
      gradient: "from-purple-600 via-pink-600 to-rose-600",
      from: "from-purple-500",
      to: "to-pink-500",
      darkFrom: "dark:from-purple-500",
      darkTo: "dark:to-pink-900",
    },
    orange: {
      primary: "from-orange-600 to-red-600",
      secondary: "from-orange-500 to-red-500",
      text: "text-orange-700 dark:text-orange-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-orange-600 dark:hover:text-orange-400",
      gradient: "from-orange-600 via-red-600 to-rose-600",
      from: "from-orange-500",
      to: "to-red-500",
      darkFrom: "dark:from-orange-500",
      darkTo: "dark:to-red-900",
    },
    red: {
      primary: "from-red-600 to-rose-600",
      secondary: "from-red-500 to-rose-500",
      text: "text-red-700 dark:text-red-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-red-600 dark:hover:text-red-400",
      gradient: "from-red-600 via-rose-600 to-pink-600",
      from: "from-red-500",
      to: "to-rose-500",
      darkFrom: "dark:from-red-600",
      darkTo: "dark:to-rose-800",
    },
    yellow: {
      primary: "from-yellow-500 to-orange-500",
      secondary: "from-yellow-400 to-orange-400",
      text: "text-yellow-700 dark:text-yellow-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-yellow-600 dark:hover:text-yellow-400",
      gradient: "from-yellow-500 via-orange-500 to-red-500",
      from: "from-yellow-500",
      to: "to-orange-500",
      darkFrom: "dark:from-yellow-500",
      darkTo: "dark:to-orange-700",
    },
    cyan: {
      primary: "from-cyan-600 to-blue-600",
      secondary: "from-cyan-500 to-blue-500",
      text: "text-cyan-700 dark:text-cyan-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-cyan-600 dark:hover:text-cyan-400",
      gradient: "from-cyan-600 via-blue-600 to-indigo-600",
      from: "from-cyan-500",
      to: "to-blue-500",
      darkFrom: "dark:from-cyan-500",
      darkTo: "dark:to-blue-700",
    },
    pink: {
      primary: "from-pink-600 to-rose-600",
      secondary: "from-pink-500 to-rose-500",
      text: "text-pink-700 dark:text-pink-400",
      subtext: "text-dark dark:text-white",
      hover: "hover:text-pink-600 dark:hover:text-pink-400",
      gradient: "from-pink-600 via-rose-600 to-red-600",
      from: "from-pink-500",
      to: "to-rose-500",
      darkFrom: "dark:from-pink-500",
      darkTo: "dark:to-rose-800",
    },
    // black: {
    //   primary: "from-gray-900 to-black dark:to-white",
    //   secondary: "from-gray-800 to-black",
    //   text: "text-gray-900 dark:text-gray-200",
    //   subtext: "text-black dark:text-white",
    //   hover: "hover:text-gray-800 dark:hover:text-gray-300",
    //   gradient: "from-black-900 via-black-800 to-black",
    //   from: "from-gray-500",
    //   to: "to-black",
    //   darkFrom: "dark:from-gray-800",
    //   darkTo: "dark:to-black",
    // },
    // white: {
    //   primary: "from-gray-100 to-white",
    //   secondary: "from-gray-200 to-white",
    //   text: "text-gray-800 dark:text-gray-100",
    //   subtext: "text-dark dark:text-white",
    //   hover: "hover:text-gray-700 dark:hover:text-gray-300",
    //   gradient: "from-gray-100 via-gray-200 to-white",
    //   from: "from-gray-200",
    //   to: "to-white",
    //   darkFrom: "dark:from-gray-300",
    //   darkTo: "dark:to-gray-100",
    // },
  };

  return colors[color as keyof typeof colors] || colors.blue;
};
